services:
  postgres:
    image: postgres:14.9-alpine3.18
    environment:
      - 'POSTGRES_DB=movie-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/root/redis
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redis123
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
volumes:
  db:
    driver: local
