services:
  postgres:
    image: postgres:14.9-alpine3.18
    environment:
      - 'POSTGRES_DB=movie-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
